language: cpp

compiler:
  - gcc
  # - clang

install:
  - 'echo -ne "\n" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"'
  - 'export PATH="$HOME/.linuxbrew/bin:$PATH"'
  - 'brew update'
  - 'brew install patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, mpfr, libmpc, isl, gcc, bzip2, boost, makedepend, openssl, pkg-config, curl, libidn, cmake'
  - 'brew install --verbose cpprestsdk'
  # - 'brew install influxdb'

script:
  - "ls ~/.linuxbrew/Cellar/*"
  # - "make -C build/linux/gmake config=release_x64"
