language: cpp

compiler:
  - gcc
  # - clang

addons:
 apt:
  sources:
   - boost-latest
   - ubuntu-toolchain-r-test
  packages:
   - g++-5
   - libboost1.55-all-dev
   - libssl-dev

cache:
 - apt

install:
  - 'echo -ne '\n' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"'
  - 'PATH="$HOME/.linuxbrew/bin:$PATH"'
  - 'brew update'
  - 'brew install cpprestsdk influxdb openssl'

before_script:
  - export CXX="g++-5"

script:
  - "ls ~/.linuxbrew/Cellar"
  # - "make -C build/linux/gmake config=release_x64"
