version: 1.0.{build}
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
configuration: Release
platform: x64
before_build:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  parallel: false
  verbosity: detailed