version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: x64
build_script:
- cmd: >-
    git submodule update --init --recursive

    nuget restore build\influxdb-cpp-rest.sln

    "C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" build\influxdb-cpp-rest.sln /property:Configuration=Release /property:Platform=x64

    wget https://dl.influxdata.com/influxdb/releases/influxdb-1.2.4_windows_amd64.zip

    src\script\test.bat build\x64\Release